### ISSUE TITLE
New sources CSV export 

### ISSUE THREAD

**Issue by brianalden** [transientskp/banana#109]
When trying to export new sources to a CSV file there is an error. This appears to happen regardless of the dataset being worked with.  Pasted below is the error received from one of the datasets.

ValueError at /vlo_bapy_msss_force_corr/newsources/
invalid literal for int() with base 10: 'TRAP dataset'
Request Method:	GET
Request URL:	http://banana.transientskp.org/master/vlo_bapy_msss_force_corr/newsources/?format=csv&dataset=TRAP%20dataset
Django Version:	1.8.3
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: 'TRAP dataset'
Exception Location:	/srv/banana/master/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py in get_prep_value, line 1868
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/srv/banana/master/banana',
 '/srv/banana/master/venv/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/srv/banana/master/venv/lib/python2.7/site-packages/git/ext/gitdb',
 '/srv/banana/master/venv/lib/python2.7/site-packages/gitdb/ext/smmap']
Server time:	Wed, 4 Nov 2015 05:04:39 +0100

**Comment by gijzelaerr** [comment]
ok, this is probably just a typo in the csv newsource template, I think there must be something like `newsource.dataset` which should be `newsource.dataset_id`. Not sure why the test suite doesn't fail on this.
