### ISSUE TITLE
Interface bugs on 'augmentedrunningcatalog' page.

### ISSUE THREAD

**Issue by timstaley** [transientskp/banana#112]
If you click through to view the augmented runningcatalog, a couple of bugs are immediately obvious:

 - There's a formatting error, so the table doesn't have a clear white background.
 - The sidebar is missing the button listing different pages for this dataset.

**Comment by gijzelaerr** [comment]
OK I think I was a bit hasty here and just completely forgot about this.

*but* we won't need the augmentedrunningcatalog view anymore once we switch to using the varmetric table.

**Comment by timstaley** [comment]
Ah yeah, sounds good :)

**Comment by gijzelaerr** [comment]
we ditched the augmentedrunningcatalog view
