### ISSUE TITLE
Running Catalog List Doesn't Load

### ISSUE THREAD

**Issue by ycendes** [transientskp/banana#114]
This started this evening on all my running catalog pages when I just try to click on any of them, in all my databases For example, here: http://banana.transientskp.org/master/vlo_SB002cendes/varmetric/?dataset=12

The error I get is as follows:
```
ProgrammingError at /vlo_SB003cendes/varmetric/
relation "varmetric" does not exist
LINE 1: SELECT COUNT('*') AS "__count" FROM "varmetric" INNER JOIN "...
                                            ^
Request Method:	GET
Request URL:	http://banana.transientskp.org/master/vlo_SB003cendes/varmetric/?dataset=18
Django Version:	1.8.3
Exception Type:	ProgrammingError
Exception Value:	
relation "varmetric" does not exist
LINE 1: SELECT COUNT('*') AS "__count" FROM "varmetric" INNER JOIN "...
                                            ^
Exception Location:	/srv/banana/master/venv/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/srv/banana/master/banana',
 '/srv/banana/master/venv/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/srv/banana/master/venv/lib/python2.7/site-packages/git/ext/gitdb',
 '/srv/banana/master/venv/lib/python2.7/site-packages/gitdb/ext/smmap']
Server time:	Tue, 15 Dec 2015 00:07:12 +0100
```

Please look into this as soon as you can, as I am suddenly *very* limited in what I can do if I can't easily access the running catalogs!

**Comment by gijzelaerr** [comment]
The banana interface and trap version don't match, current banana master is
only compatible with recent trap databases, for example 3.0rc. I suggest
you rerun your dataset with 3.0rc. Sorry but that is a consequence of using
unreleased software, basically using nigtlies and current master is
officially only for testing. This is why I want to push out a release - to
prevent these kind of problems.
Op 15 dec. 2015 1:11 a.m. schreef "ycendes" <notifications@github.com>:

**Comment by gijzelaerr** [comment]
this is not a issue with TraP, so closing the issue.
