### ISSUE TITLE
"celestial_pixel_scale" image error

### ISSUE THREAD

**Issue by ycendes** [transientskp/banana#115]
Banana seems to be expecting a field “celestial_pixel_scale” which is not in the database for any images (see for an example:  http://banana.transientskp.org/master/vlo_cendescandidateSB003/image/1/).  As such, apparently the individual image pages do not appear to work with Release 3.0rc.

For the record, I recreated the currently used databases using the latest release using /soft/trap/r3.0rc/init.sh on struis, and Antonia has also run a different set of fits files through TraP to check on Banana with the same result.  I don't see any other issues on Banana regarding this.

**Comment by gijzelaerr** [comment]
This has to do with aplpy. We are depending on a newer version of aplpy now (1.0), but the old (0.9.12) was still installed for the master banana virtualenv. Updating as we speak.

**Comment by gijzelaerr** [comment]
yep. that fixed the problem!
