### ISSUE TITLE
Running catalogue csv not pulling correct catalogues

### ISSUE THREAD

**Issue by ajstewart** [transientskp/banana#117]
From the running catalogue list page (List of Running Catalogs with Variability Metrics) when I select csv format it returns a list of running catalogues not associated with that dataset.

For example my first RC ID is 14503 but the csv returns catalogues with IDs ranging from 11000 - 14000 in a mixed order. I wondered if it was just pulling a different dataset but it seems to pull IDs from a range of datasets, so I'm not quite sure what's going on.

**Comment by gijzelaerr** [comment]
fixed, thanks!
