### ISSUE TITLE
Offset Lightcurve point pop-up box so it doesn't cover the point. 

### ISSUE THREAD

**Issue by mkuiack** [transientskp/banana#124]
The light curve plot points are clickable links that lead to the extracted source information page, which is awesome! when the pop-up isn't covering the plot point/link and blocking it. 

The point is highlighted when moused over so the pop-up box doesn't need to be super near the point.  Offset it so it can't block the link. 

Also add seconds to all timestamps. 
<img width="1440" alt="screen shot 2016-08-02 at 12 58 24" src="https://cloud.githubusercontent.com/assets/14295490/17326365/389e98a8-58b1-11e6-8d20-d94747e24d26.png">

**Comment by gijzelaerr** [comment]
what about making the `extractioned source` number clickable? it would redirect you to the same page

**Comment by mkuiack** [comment]
You mean in the popup window? 
That would be great.

**Comment by mkuiack** [comment]
Can you add seconds to the time in that popup while you're at it?

**Comment by gijzelaerr** [comment]
ok added seconds. I can't add a link to the tooltip. I updated highcharts to 4.2.7, i think it is a bit better in redering the overlay thingy. what do you think? banana master on vlo should be updated
