### ISSUE TITLE
various pages don't load for banana 4

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/banana#127]
I've received this feedback from the US:

New sources, Quality Control, and Number of Sources take a very long time to load (Internal Server Error)
If i try to click on the images in the Running Catalogs page it does not load. Total image count page works, but i can't select individual images.

**Comment by mkuiack** [comment]
Try without saving the images.

**Comment by gijzelaerr** [comment]
They already did, that solves all problems

Op 11 okt. 2016 11:37 a.m. schreef "Mark" <notifications@github.com>:

**Comment by gijzelaerr** [comment]
I think I solved the problems for the slow loading time for the image related pages. Technical clarification: I put the image data now in a separate table so the loading of the image metadata is not affected. https://github.com/transientskp/tkp/commit/d69ad7c7afc42b587afcea0470c04d3c24803e89

**Comment by gijzelaerr** [comment]
zack & zack have verified that these problems are resolved, will do a 4.0rc2 soon.
