### ISSUE TITLE
Add Previous image by time button to Image page.

### ISSUE THREAD

**Issue by mkuiack** [transientskp/banana#128]
Why not be able to go forwards _and_ backwards?

**Comment by gijzelaerr** [comment]
done https://github.com/transientskp/banana/commit/72702ac9430ed0389dcc5fe83da1ded63c571f6e

**Comment by mkuiack** [comment]
banana "latest master" page not loading since this update.

**Comment by gijzelaerr** [comment]
i experience no problems

http://banana.transientskp.org/master/vlo_test_40rc2/image/17/

**Comment by mkuiack** [comment]
that loads for me but http://banana.transientskp.org/master does not

**Comment by mkuiack** [comment]
If I follow your link back to the /master page by clicking "Databases" it will load. but if I go from http://banana.transientskp.org and use the "Latest Master" link it does not.

**Comment by gijzelaerr** [comment]
it does for me, takes about 3 seconds

**Comment by mkuiack** [comment]
#stillwaiting
