### ISSUE TITLE
Banana fails with database name containing "."

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/banana#51]
The front page of the current master of Banana will not load with new database created using Release 2 TraP, the website gives the error:

`
error 500

O no! Reverse for 'datasets' with arguments '('XXXXXXXXXX',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['(?P<db>\\w+)/$']
`

where XXXXXXXXXX  is blanking out my database name. Additionally I cannot use the .../master/XXXXXXXXXX page but the equivalent pages for other databases still work.

I think this is because I used "." in the database name, as I created a second database without "." in the name and the individual database page worked fine. Note that TraP seems to work completely fine with a database name containing ".".

However, even if I delete the problematic database, Banana still will not load the first page - giving the same error message. So it is somehow remembering this broken database name.

Banana needs to be corrected so that it will work with any database names that TraP allows you to create and use... If this is a fundamental problem, then TraP should not allow you to create a database with that name.

(See private message for specific details)

**Comment by gijzelaerr** [comment]
probably simple to fix, will have a look tomorrow.

**Comment by gijzelaerr** [comment]
when the TKP PR is merged this issue can be closed.
