### ISSUE TITLE
Ability to Change Contrast Levels of an Image

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/banana#52]
Much like what is talked about in this issue about the thumbnails #4616, I think being able to change image levels on the fly would be a big help - of course how tricky that might be I'm not sure.

original issue
https://support.astron.nl/lofar_issuetracker/issues/5411

**Comment by gijzelaerr** [comment]
this is tricky. The cyberska viewer can do this, but requires a pureweb license.

https://github.com/radio-astro/cyberska_viewer

**Comment by timstaley** [comment]
[JS9](http://js9.si.edu/) and Aladin (which we already partially use, right?) might be possible options, too.

**Comment by gijzelaerr** [comment]
please follow issue #95
