### ISSUE TITLE
Detailed Image View - Make zoomable to see the source fit quality

### ISSUE THREAD

**Issue by ajstewart** [transientskp/banana#58]
I've come across a situation where it would be really useful to see in more detail how the source has been extracted by TraP. For example I suspect that a source has been flagged as interesting because some of the flux is being missed by the fit with certain beam shapes (especially when using forced beam). So it would be nice to inspect the image a bit more carefully, by being able to zoom in on the detailed image.

**Comment by gijzelaerr** [comment]
Maybe this is something for: visiomatic

http://www.visiomatic.org/software/visiomatic

That may also solve #48 and #59, by having the fit circles as optional overlay layers.

There is also a visiomatic docker image available: radioastro/visiomatic

https://github.com/radio-astro/docker-visiomatic

**Comment by ajstewart** [comment]
Looking at the demos that would be really nice if it was possible to include!

May also provide a method for #52 in some from? (I think the place for this is the 'detailed view')

**Comment by gijzelaerr** [comment]
this would be solved with the switch to JS9

https://github.com/transientskp/banana/issues/95

**Comment by gijzelaerr** [comment]
please follow issue #95
