### ISSUE TITLE
Detailed Image View - Toggle Source Fit Circles by Type

### ISSUE THREAD

**Issue by ajstewart** [transientskp/banana#59]
Somewhat expanding the idea presented in #48 - if would be nice to be able to hide/show the extraction circles in the detailed image view by extraction type. For example hide all blind extractions and only show forced extractions. Sometimes they are a bit on top of each other and would just make things a bit clearer.

**Comment by gijzelaerr** [comment]
this would be solved with the switch to js9

https://github.com/transientskp/banana/issues/95

**Comment by gijzelaerr** [comment]
closing this issue, please follow issue #95
