### ISSUE TITLE
State the number of blind extractions from an image separately

### ISSUE THREAD

**Issue by timstaley** [transientskp/banana#60]
(Migrated from https://github.com/transientskp/tkp/issues/394 ) 
ajstewart commented 5 days ago
Personally I feel it would be useful to somewhere differentiate between the number of blind sources extracted from an image and the number of 'forced fits'. This would be to answer simple questions such as how many sources on average are extracted from images. It may also help with manual attempts at quality control, if suddenly the number of sources extracted drops then this is an easy sign to spot.

This also leads to the histogram on the front page of a run. For every run I do it steadily just increases to approximately double the number sources actually found in an image and levels off. I would find it more useful to know how many sources are actually found in each individual image rather than this cumulative representation. Though this preference may not be shared.

**Comment by ajstewart** [comment]
I'm not sure about others but this is feature is something I would really appreciate and have found myself wishing it was there numerous times. Being able to answer the questions of 'how many sources am I detecting in my images' is really valuable.

If there is any way this could be included in 3.0 then that would be really, really helpful.

**Comment by gijzelaerr** [comment]
@ajstewart implemented this so we can close this issue!
