### ISSUE TITLE
Running Catalog Page Very Slow

### ISSUE THREAD

**Issue by ajstewart** [transientskp/banana#64]
I feel like I've seen this talked about a while ago but when there are a lot of sources in the database, I'm finding accessing the running catalogue page extremely slow. To the point where I leave the tab open and go and do something else for 5 minutes. The same is true when attempting to re-order the data by a specific column.

I don't experience issues with any other area.

**Comment by gijzelaerr** [comment]
Actually this is more of a TRAP problem, banana just visualises the results.

I was afraid that would become a problem in the long run. There is no easy solution to this for now, but I think this is a quite important issue since it is very annoying and will get worse as the database grows.

**Comment by ajstewart** [comment]
Thanks for acknowledging it - I was wondering if this would be a TraP issue more so than banana when I posted, perhaps it should be moved? Or another issue created on the TraP side.

**Comment by AntoniaR** [comment]
As my databases are forever growing and things are just getting slower, I've been thinking about this issue for a while. I think (though still need to test this) that for very large datasets it might make sense to just have multiple databases as a short term solution. i.e. one database for a specific project so a specific user would have multiple databases. I think that would help speed things up again for individual datasets.
However, I remember that we were discouraged early on from having many databases - is this still the case? Are there likely to be computing issues when users have lots of databases?

**Comment by gijzelaerr** [comment]
I think in case of MonetDB you don't want to have a lot of databases, but for PostgreSQL it doesn't really matter AFAIK.

So yes, a workaround for now is to just use a database per project and keep the database small.

**Comment by ajstewart** [comment]
This is what I've always done - I usually have multiple databases on the go for multiple projects (I've only ever used postgres for a while now). My latest database has got to the point where I'm seeing significant slow down again. I find even trying to navigate directly to the Run Cat ID I want very slow, I guess this is down to how it accesses this entry?

In this database I am just running the same data through, usually each day, with the addition of 1 or 2 new images (now about 66 images or so). But I just wanted to check, setting the persistence id won't help with anything here right? I do not change the settings at all in this particular database to run the TraP, so I was hoping for a mode where it effectively carries on where it left off - the images are the same, sources extracted are the same, it just needs to add the results from the new image. But as far as I can see, no matter how I run the TraP it's going to run the source extraction each time, filling the database with the same sources over and over? Do I run it with the persistence id selected but only feed it the new images I want looked at?

This is a unique case and would change if I suddenly wanted to change the extraction settings I am using. Apart from just creating a new database now and again I don't see an immediate way around it. Out of interest what makes it so slow? I don't know anything about it but is banana accessing running catalogues via the entire database? I understand it perhaps taking a long time to list all the running catalogues but I'd be interested to know why clicking directly on a single Run Cat id also takes a long time, as I mentioned at the beginning.

**Comment by AntoniaR** [comment]
By using dataset_id = <existing dataset id> will make TraP process all the images in images_to_process.py and add them to the dataset id that you write in there.

Say you have processed the first 10 images and TraP gave it a dataset id of 4.
The following day you have 10 more images which you want to append to dataset 4.
Change dataset_id=-1 to dataset_id=4 in the job_params.cfg
Change the images_to_process.py file to point to ONLY the new images. I suspect that you are assuming TraP will not process the same images again, but that is not the case - it will process every image in images_to_process.py meaning you are duplicating the existing images.

**Comment by gijzelaerr** [comment]
this should be solved when we switch to the precalculated varmetric way of processing and representing data:

https://github.com/transientskp/tkp/pull/469

**Comment by gijzelaerr** [comment]
the varmetric PR has been accepting, this should solve the speed issues. Please reopen if you still experience performance problems with the runningcatalog view.
