### ISSUE TITLE
Histogram displaying typical RMS noise properties of images

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/banana#71]
On the first page of Banana, it would be great to have a histogram of the RMS noise values in all the images in the dataset. The RMS noise is one of the most useful quality control checks and being able to visualise it is great. It would be cool if this could have different coloured bars for each of the observing frequencies. I've attached a typical histogram from one of my datasets. I have fitted the distribution with a Gaussian. The mean and 1 sigma ranges would also be very useful numbers to quote, but I'm not sure how computationally expensive this would be.
![rms_allmhz](https://cloud.githubusercontent.com/assets/1759492/6931849/ba7241d4-d85d-11e4-826f-7a0e92c0d99a.png)

**Comment by gijzelaerr** [comment]
This is actually not so hard to do, since we store the RMS values in the database for quality control.

http://tkp.readthedocs.io/en/r3.0/devref/database/schema.html#image

we should use the RMS_QC column right?
```
rms_qc: RMS for quality-control. This is the sigma-clipped RMS value from the central region of the image, calculated in the persistence step.
```

**Comment by AntoniaR** [comment]
Yes, that's the correct column. Thanks!

**Comment by gijzelaerr** [comment]
@AntoniaR do you have the script that generated that graph somewhere? saves me time.

**Comment by AntoniaR** [comment]
This is theoretically in the script: https://github.com/transientskp/scripts/tree/master/TraP_fits_QC (see plothist in tools.py) but you've spotted a bug so I need to check.
(see also this issue https://github.com/transientskp/tkp/issues/512)

**Comment by AntoniaR** [comment]
This is the actual script that generated this specific plot, it does a few other things as well which are not needed for this issue.
https://github.com/AntoniaR/scripts/tree/master/TraP_QC_diagnostics

Specifically, this plot needs this code https://github.com/AntoniaR/scripts/blob/master/TraP_QC_diagnostics/TraP_QC_diagnostics.py#L1-L52

The database querying part of my code unfortunately now only works for versions of TraP release 1 or 2 due to the switch to SQLAlchemy in release 3.

**Comment by gijzelaerr** [comment]
@AntoniaR what is reason why the script accepts 2 dataset ID's?

**Comment by AntoniaR** [comment]
As I mentioned previously, there are things in this script that are not required for this issue. The second half of the script does some quality control tests using the extracted sources in each of the images. At the time of writing that specific version of the script, TraP only output RMS values for rejected images so I had to run TraP twice (once to reject the images and second to get the source parameters) and hence needing two dataset IDs. To complete this plot, you only need 1 dataset ID and the code lines 1-52 as mentioned previously.
This is explained in the README on this page: https://github.com/AntoniaR/scripts/tree/master/TraP_QC_diagnostics

**Comment by gijzelaerr** [comment]
just checking, it was not directly obvious what was required and what not.

**Comment by gijzelaerr** [comment]
Ok I think I successfully implemented this. Since nobody has a schema 39 database yet I've set one up with AARTFAAC data to visualise the results:

http://banana.transientskp.org/master/vlo_schema39/dataset/1/

It is quite slow, and the results don't always seem to be deterministic oddly enough. I will debug this more  once I am in Amsterdam.

**Comment by gijzelaerr** [comment]
Correction, the graphs are deterministic, just broken for some frequencies. I think a good way forward is that I rewrite @AntoniaR into a IPython notebook so she can fiddle with the graphs, and then we implement this again in banana.

**Comment by gijzelaerr** [comment]
there is a notebook available here: https://github.com/transientskp/notebooks/blob/master/calculate%20RMS%20quality%20control.ipynb

**Comment by AntoniaR** [comment]
Great to see the first versions of these plots and it's going to be extremely useful - these plots are precisely what I was after and the only addition that would be nice is writing the Gaussian fit parameters somewhere on the page for each plot, then we can read off the mean RMS and uncertainty immediately for a given dataset. There is nothing else I can think of that I would like to do to improve them.

However I'm not at all surprised that it is slow, my code was only ever intended as a guide for this issue... I am sure there are far more efficient ways in Python for fitting Gaussian distributions or speeding up the code that I do not know about. Also, I'm do not know what you mean by broken for some frequencies, as all those plots looked fine to me... Finally, this issue is linked to this issue: https://github.com/transientskp/tkp/issues/512 so I think we should use the same code for fitting.

If it is not possible to speed this code up then, of course, we will have to investigate methods that are faster and theoretically should give the same approximate result (e.g. median sigma clipping instead of a Gaussian fit).
