### ISSUE TITLE
Highcharts light curve on Runcat page failure with large number of data points

### ISSUE THREAD

**Issue by AntoniaR** [transientskp/banana#77]
When there are a large number of data points (>1000?) in the light curves the Highcharts light curve fails to load. I have attached an example screenshot to illustrate the issue and will also post an example webpage to HipChat. Is there a maximum number of data points for Highcharts? If this is a Highcharts limitation, perhaps we could also have a non-interactive light curve option until this issue is resolved?

![issue_example](https://cloud.githubusercontent.com/assets/1759492/7151217/0eb4978a-e36a-11e4-9b13-96cc7a4db615.png)

**Comment by ajstewart** [comment]
I've also seen this recently - it is to do with the 'turboThreshold' parameter in highcharts:

http://api.highcharts.com/highcharts#plotOptions.series.turboThreshold

>When a series contains a data array that is longer than this, only one dimensional arrays of numbers, or >two dimensional arrays with x and y values are allowed. Also, only the first point is tested, and the rest >are assumed to be the same format. This saves expensive data checking and indexing in long series. >Set it to 0 disable. Defaults to 1000.

I manually tested bumping this value up to 2000, and indeed the light curve did then plot fine with no significant slow down (the series in question was something like 1700 in length). But of course to what value this threshold should be to try and avoid it in the future is a difficult question, 5000, 10000, 30000? Then I would be concerned of how long it takes to generate the light curve. But I think a limit is better than disabling it. How many data points did your example have @AntoniaR?

Either way, unless we discover that having the threshold really high doesn't impact the performance, it either needs a static substitute for long data series or restructure the way the light curve is plotted such that it is only fed the x and y values as mentioned in the turboThreshold description. Though looking at how it is currently plotted such a re-write might be more annoying that it's worth?

**Comment by AntoniaR** [comment]
Thanks for investigating this Adam!

I agree that we shouldn't disable this at the moment and we should investigate/think about the options more. There are a number of things that we need to do to Banana to make it scalable to huge datasets, so I think we should wait for a re-write until we have discussed all the issues.

In the I think for now, we should just bump this limit up - I don't think highcharts is the limiting factor when loading those webpages :) My examples have >2000 datapoints but am now limiting the number of images I process at once (due to other issues). What about making it 5000 and seeing if there are any problems?

**Comment by ajstewart** [comment]
I agree with the temporary bumping of the turboThreshold and have done so in PR #85 as referenced above. This gives a bit of breathing room while we consider what exactly to do with the light curve plotting.
