### ISSUE TITLE
More information on new sources overview page

### ISSUE THREAD

**Issue by ajstewart** [transientskp/banana#80]
I thought it might be good to have a bit more information on the new sources overview list page. Table fields such as flux information (mean, max, median) and the eta and nu values.

I find myself flicking back and forth between the run cat and new sources list pages to quickly get this information and also it might be nice to be able to sort the new sources by e.g. flux.

I guess this would have to be pulled from the associated run cat, would it be simple? I'm also wondering if it would slow it down significantly.

**Comment by gijzelaerr** [comment]
@ajstewart so the newsources page is actually useful? Shouldn't we add this information in the runningcatalogs view?

**Comment by ajstewart** [comment]
It's useful in the sense that it's a filtered list of new sources only, without having to load the entire running catalogue.

But you're right, if I understand your question correctly, essentially it's a 'show new sources only' button on the running catalogue page.

**Comment by gijzelaerr** [comment]
I think since we now have a fast runningcatalog view again, this issue has become obsolete. Please reopen if you think otherwise.
