### ISSUE TITLE
Individual extracted source pages - minor changes needed 

### ISSUE THREAD

**Issue by jbroderick1** [transientskp/banana#83]
e.g. http://lofar1/banana-master/jess_v2_postgres/extractedsource/643128/

* Position (Sexagesimal)  - RA error should have subscript s, not ''
* Peak flux (Jy)  - should be Jy beam^{-1}
* Semi-major axis and Semi-minor axis - the unit, 'arcsec', gets cut off. Make column wider?
* Position (Sexagesimal) - put spaces around +/- symbol, like in the line above 
* Position (Sexagesimal) - is it possible to include leading zeros?

**Comment by jbroderick1** [comment]
Also 'Sexagesimal' shouldn't be capitalised if 'decimal' isn't. Yes I realise I am being incredibly pedantic :-)

**Comment by ajstewart** [comment]
@jbroderick1 Does this look ok?

![extracted-source-detail-edited](https://cloud.githubusercontent.com/assets/3306161/8440214/a8be2e74-1f68-11e5-8d20-66755b8332b6.png)

**Comment by jbroderick1** [comment]
Looks perfect, except for one thing - probably no need for a leading zero on the sexagesimal RA error. Just the coordinates....

**Comment by ajstewart** [comment]
Ah yes, I've reverted that

![extracted-source-detail-edited2](https://cloud.githubusercontent.com/assets/3306161/8451391/e8d10a0a-1fda-11e5-8816-ae70ad245c7b.png)

**Comment by jbroderick1** [comment]
Ok I think this issue has been fully fixed.
