### ISSUE TITLE
Running Catalog pages - minor changes 

### ISSUE THREAD

**Issue by jbroderick1** [transientskp/banana#84]
e.g. http://lofar1/banana-master/jess_v2_postgres/runningcatalog/22414/

- Max/mean/median flux densities - put in the unit? Should it be specifically mentioned that this means integrated, rather than peak flux densities? 
- Peak flux / Peak Flux err - unit should be Jy beam^{-1} 
- Sexagesimal coordinates - leading zeros? E.g. +58° 9′ 7.4″  --> +58° 09′ 07.4″

**Comment by ajstewart** [comment]
@jbroderick1 how is this?

![runningcat-detail-edited](https://cloud.githubusercontent.com/assets/3306161/8440258/ffc1ce60-1f68-11e5-8387-515f2fed4a86.png)

**Comment by jbroderick1** [comment]
Yep, looks good, although I spotted one more thing: change 'mm:ss' to 'mm:ss.s'.

**Comment by ajstewart** [comment]
Sure:

![runningcat-detail-edited2](https://cloud.githubusercontent.com/assets/3306161/8451347/8fbca4a6-1fda-11e5-8e6a-45c81c17da84.png)

**Comment by jbroderick1** [comment]
Ok I think this issue has been fully fixed.
