### ISSUE TITLE
Time between Lightcurve and Image is Off

### ISSUE THREAD

**Issue by ycendes** [transientskp/banana#92]
It appears that the lightcurve generated in the running catalog's image is off of the image file's time stamp by one hour.  See: http://banana.transientskp.org/master/vlo_testcorrectra/runningcatalog/27/ for an example (the image's time is listed in UTC)

Just checking if the lightcurve is perhaps in local time or what?  It is probably best to keep all time in UTC as a user, or at least that would be my preference lest I get confused.

**Comment by gijzelaerr** [comment]
this is actually an issue with AARTFAAC

https://gist.github.com/gijzelaerr/0895d9f9578798922f40

**Comment by gijzelaerr** [comment]
moved issue, closing this one
