### ISSUE TITLE
Replace banana image viewer with JS9

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/banana#95]
Currently the banana image viewer is quite slow and sometimes hard to interprate. We need a more interactive replacement. Aladin lite looks like a itneresting replacement candidate. We already use it, but we don't embed the actual radio image in it yet.

JS9 looks like the thing we need! http://js9.si.edu/

**Comment by timstaley** [comment]
Related: https://github.com/transientskp/banana/issues/52

**Comment by gijzelaerr** [comment]
implementing in this PR https://github.com/transientskp/banana/pull/105

**Comment by gijzelaerr** [comment]
I have implemented this for the 'detailed view' for banana. see an example here:

http://banana.transientskp.org/master/vlo_AR_DDT/bigimage/95/

Question now is, does this work properly? I find JS9 a bit slow sometimes, and somehow it takes a couple of second to load up an image when I run the code on a production server (it is instant when ran on my local machine).

Hopefully stuff we can solve, I hope it is already useful. Please share your experiences.

**Comment by gijzelaerr** [comment]
lets just close this issue since it just seems to work.
